// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prxsxltzzfjgmazkwdoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByeHN4bHR6emZqZ21hemt3ZG9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMDEzODIsImV4cCI6MjA2Mzc3NzM4Mn0.1dVajgH2MV4OLiNd-t4fG2gcICtdRnnEpkEyWES0brQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);